eureka:
  client:
    register-with-eureka: true
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/communication/**
  application:
    name: gateway

